### PR TITLE
Support custom encodings

### PR DESCRIPTION
**Pull request by ochakov**
Add setEncoding command to change string encoding sent to the printer

### CODE REVIEW

**Comment by CesarBalzer** [comment]
Very nice functionality, I will be updating the readme with the description of how this new function works, thanks for the contribution @ochakov

**Comment by andreszs** [comment]
Hi, can you please merge this commit? Thanks

**Comment by CesarBalzer** [comment]
Hi @andreszs, sorry, i already forgot i had a pending pull, now i have this new change, thank you very much!

**Comment by andreszs** [comment]
Also, I've forked the plugin to add an `encoding` parameter to the text-printing methods. Instead of hard-coding a pre defined charset in the JAVA file, it will receive the encoding as a **second argument**.

If you agree with this change I'll create a PR here and close my branch, please let me know. With my PR the encoding is sent like this:

BTPrinter.printText(function(data){
    console.log("Success");
    console.log(data);
},function(err){
    console.log("Error");
    console.log(err);
}, "String to Print", "ISO-8859-1");

**Pull request merged**
